import NotificationProvider from '@/components/notification-provider';
import './global.css';

export const metadata = {
  title: 'Todo . A sample Todo App',
  icons: {
    icon: '/circle-plus.svg',
  },
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        data-new-gr-c-s-check-loaded="14.1232.0"
        data-gr-ext-installed=""
      >
        <NotificationProvider>{children}</NotificationProvider>;
      </body>
    </html>
  );
}
